#!/bin/bash

if [[ $# -eq 0 ]]; then
    docker exec -it frappe bash
elif [ "$1" == 'setup' ] && [ "$2" == 'docker' ]; then
        if [ "$3" == '--swarm-mode' ]; then
            echo "Docker swarm mode is not currently supported"
        else
            docker-compose up -d
        fi
elif [ "$1" == '-c' ]; then
    shift
    user=$1
    shift
    docker exec -iu "$user" frappe bash -c "$@"
elif [ "$1" == '-h' ]; then
    echo "$0 [-h] | [ -c frappe | root <command to run> ] [ <command to send to bench> ]"
    echo ""
    echo "$0 extends the Frappe Bench tool, and is used like it. However, it extends the tool in a few places."
    echo "Usage:"
    echo "    $0"
    echo "                Launches you into an interactive shell in the container as user frappe"
    echo "    $0 setup docker"
    echo "                Starts and builds the docker containers using \"docker-compose up -d\""
    echo "    $0 -c frappe | root <command to run>"
    echo "                Runs a command in the container, as the selected user"
    echo "    $0 -h"
    echo "                Shows this help message"
    echo "    $0 <command to send to bench>"
    echo "                Runs a command in bench, i.e. $0 new-site site1.local = bench new-site site1.local"
else
    IFS=" "
    docker exec -it frappe bash -c "bench $*"
fi
